version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: phonebook
      POSTGRES_PASSWORD: phonebook
      POSTGRES_DB: phonebook
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - phonebook-network

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/phonebook
      - DB_USERNAME=phonebook
      - DB_PASSWORD=phonebook
    networks:
      - phonebook-network

volumes:
  pgdata:

networks:
  phonebook-network:
