services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: phonebook
      POSTGRES_PASSWORD: phonebook
      POSTGRES_DB: phonebook
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: